### ISSUE TITLE
Not able to run test by command 'npm test'

### ISSUE THREAD

**Issue by vijay-k-singh** [igniteram/protractor-cucumber-allure#17]
when trying to run test after doing npm install, i am getting following error:
[23:42:12] I/launcher - Running 1 instances of WebDriver
[23:42:12] I/direct - Using ChromeDriver directly...
[23:42:12] E/direct - Error code: 135
[23:42:12] E/direct - Error message: Could not find update-config.json. Run 'webdriver-manager update' to download binaries.
[23:42:12] E/direct - Error: Could not find update-config.json. Run 'webdriver-manager update' to download binaries.
    at IError (/Users/vijaysingh/Desktop/cucumber/protractor-cucumber-allure-master/node_modules/protractor/built/exitCodes.js:5:1)
    at ProtractorError (/Users/vijaysingh/Desktop/cucumber/protractor-cucumber-allure-master/node_modules/protractor/built/exitCodes.js:10:9)
    at BrowserError (/Users/vijaysingh/Desktop/cucumber/protractor-cucumber-allure-master/node_modules/protractor/built/exitCodes.js:51:9)
    at Direct.getNewDriver (/Users/vijaysingh/Desktop/cucumber/protractor-cucumber-allure-master/node_modules/protractor/built/driverProviders/direct.js:62:31)
    at Runner.createBrowser (/Users/vijaysingh/Desktop/cucumber/protractor-cucumber-allure-master/node_modules/protractor/built/runner.js:194:43)
    at q.then.then (/Users/vijaysingh/Desktop/cucumber/protractor-cucumber-allure-master/node_modules/protractor/built/runner.js:338:29)
    at _fulfilled (/Users/vijaysingh/Desktop/cucumber/protractor-cucumber-allure-master/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/vijaysingh/Desktop/cucumber/protractor-cucumber-allure-master/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/vijaysingh/Desktop/cucumber/protractor-cucumber-allure-master/node_modules/q/q.js:796:13)
    at /Users/vijaysingh/Desktop/cucumber/protractor-cucumber-allure-master/node_modules/q/q.js:556:49
[23:42:12] E/launcher - Process exited with error code 135

I have tried running **webdriver-manager update**, but no luck.
Please suggest a way to fix as soon as possible.

Thank you
Vijay

**Comment by igniteram** [comment]
Can you please mention the protractor ,webdriver-manager & node versions you are using?

**Comment by vijay-k-singh** [comment]
Hi,

Please refer below details for queries: protractor ,webdriver-manager &
node versions you are using
node: v6.9.5
protractor: 5.1.1
webdriver-manager: 12.0.5

Regards,
Vijay Singh

**Comment by nkhadka** [comment]
Any update on this? Been running into the same issue.
node - v6.9.1
protractor - 5.1.2
webdriver-manager - 12.0.6

**Comment by igniteram** [comment]
@vijay-k-singh @nkhadka The above issue has nothing to do with the current framework implementation, it is just that webdriver-manager module is not able to download the driver binaries. Can you run `webdriver-manager update` through your package.json scripts like this -

```
"scripts": {
  "webdriver-update": "webdriver-manager update"
}
```
then run this command in cli - `npm run webdriver-update`

This should download the binaries, if it gives error please paste the same here so that I could have a look at that and suggest you next course of actions!

**Comment by nkhadka** [comment]
I was able to solve this by using the local `protractor` from `node_modules`. It was the global installation that was causing the problems.  Thanks for your help.
@igniteram

**Comment by igniteram** [comment]
Since the problem seems to be fixed , closing this issue!
