### ISSUE TITLE
Upgrading cuucmber-protratctor-framework and cuucmber version to latest version breaks the tests  

### ISSUE THREAD

**Issue by pnakhat** [igniteram/protractor-cucumber-allure#19]
I upgraded to below 

 "cucumber": "^2.0.0",
    "protractor": "^5.0.0",
    "protractor-cucumber-framework": "^2.0.0"

and tests now break with error below

Unhandled rejection Error: Not empty
    at TagExpressionParser.parse (C:\code\protractor-cucumber-allure-master\node
_modules\cucumber-tag-expressions\lib\tag_expression_parser.js:49:13)
    at new ScenarioFilter (C:\code\protractor-cucumber-allure-master\node_module
s\cucumber\lib\scenario_filter.js:44:52)
    at Cli.<anonymous> (C:\code\protractor-cucumber-allure-master\node_modules\c
ucumber\lib\cli\index.js:145:30)
    at next (native)
    at undefined.tryCatcher (C:\code\protractor-cucumber-allure-master\node_modu
les\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:\code\protractor-cucumber-allure-master
\node_modules\bluebird\js\release\generators.js:97:49)
    at Promise._settlePromise (C:\code\protractor-cucumber-allure-master\node_mo
dules\bluebird\js\release\promise.js:574:26)
    at Promise._settlePromise0 (C:\code\protractor-cucumber-allure-master\node_m
odules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\code\protractor-cucumber-allure-master\node_m
odules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\code\protractor-cucumber-allure-master\node_modules
\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\code\protractor-cucumber-allure-master\node_module
s\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\code\protractor-cucumber-allure-master\no
de_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by igniteram** [comment]
@pnakhat Cucumber 2.0 has lot of breaking changes and most of the syntax is changed. I have been working on the PR to integrate cucumber 2.0 changes. I will soon be releasing it once I fix the CI issues!

**Comment by igniteram** [comment]
Upgraded the project with latest cucumber 2 version, test are working fine with this version. please pull in the new changes and give it a try!

**Comment by igniteram** [comment]
closing this issue, please raise a new one if you face any issues!
