### ISSUE TITLE
Not found element stop process

### ISSUE THREAD

**Issue by aluzardo** [igniteram/protractor-cucumber-allure#3]
The problem is that some errors stop the process and I am unable to get the final report.

One example of error that stop the process https://github.com/aluzardo/protractor-cucumber-allure/tree/not-found-element-stop-process

The issue looks very similar than this https://github.com/angular/protractor/issues/876

Failing example https://travis-ci.org/aluzardo/protractor-cucumber-allure

PD. Maybe it is because I am using the framework in a wrong way.

**Comment by igniteram** [comment]
@aluzardo I would investigate on this issue, meanwhile could you downgrade to lower versions of protractor and check if it is working as expected?

**Comment by aluzardo** [comment]
Yes, you are right. Using protractor 3.3.0 everything works as expected. 

Example of result using protractor 3.3.0.

```
➜  protractor-cucumber-allure git:(not-found-element-stop-process) ✗ npm test

> protractor-cucumber-allure@1.0.0 test /Users/adolfocabrera/Mavrix/protractor-cucumber-allure
> protractor Config/config.js

[09:42:48] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[09:42:48] I/launcher - Running 1 instances of WebDriver
Feature: To search allure reports in google

cucumber event handlers attached via registerHandler are now passed the associated object instead of an event
getPayloadItem will be removed in the next major release
  @AllureScenario
  Scenario: Allure Reports Google
Wrong label: @AllureScenario
  ✓ Given I am on google page
  ✖ When I type "allure reports"
  - Then I click search button
  - Then I clear search textbox

Generated Reports/cucumber_report.html successfully.
Feature: To search cucumber in google

  @CucumberScenario
  Scenario: Cucumber Google
Wrong label: @CucumberScenario
  ✓ Given I am on google page
  ✖ When I type "cucumber"
  - Then I click search button
  - Then I clear search textbox

Generated Reports/cucumber_report.html successfully.
Feature: To search protractor in google

  @ProtractorScenario
  Scenario: Protractor Google
Wrong label: @ProtractorScenario
  ✓ Given I am on google page
  ✖ When I type "protractor"
  - Then I click search button
  - Then I clear search textbox

Generated Reports/cucumber_report.html successfully.
Failures:

1) Scenario: Allure Reports Google - Features/allure.feature:4
   Step: When I type "allure reports" - Features/allure.feature:6
   Step Definition: StepDefinitions/search.js:8
   Message:
     NoSuchElementError: No element found using locator: By(css selector, input[name='NotElementFound'])
         at WebDriverError (/Users/adolfocabrera/Mavrix/protractor-cucumber-allure/node_modules/selenium-webdriver/error.js:26:26)
         at NoSuchElementError (/Users/adolfocabrera/Mavrix/protractor-cucumber-allure/node_modules/selenium-webdriver/error.js:229:26)
         at /Users/adolfocabrera/Mavrix/protractor-cucumber-allure/node_modules/protractor/built/element.js:662:27
         at Promise.invokeCallback_ (/Users/adolfocabrera/Mavrix/protractor-cucumber-allure/node_modules/selenium-webdriver/lib/promise.js:1329:14)
         at TaskQueue.execute_ (/Users/adolfocabrera/Mavrix/protractor-cucumber-allure/node_modules/selenium-webdriver/lib/promise.js:2790:14)
         at TaskQueue.executeNext_ (/Users/adolfocabrera/Mavrix/protractor-cucumber-allure/node_modules/selenium-webdriver/lib/promise.js:2773:21)
         at /Users/adolfocabrera/Mavrix/protractor-cucumber-allure/node_modules/selenium-webdriver/lib/promise.js:2652:27
         at /Users/adolfocabrera/Mavrix/protractor-cucumber-allure/node_modules/selenium-webdriver/lib/promise.js:639:7
         at process._tickCallback (internal/process/next_tick.js:103:7)
     Error
         at ElementArrayFinder.applyAction_ (/Users/adolfocabrera/Mavrix/protractor-cucumber-allure/node_modules/protractor/built/element.js:371:27)
         at ElementArrayFinder._this.(anonymous function) [as sendKeys] (/Users/adolfocabrera/Mavrix/protractor-cucumber-allure/node_modules/protractor/built/element.js:83:30)
         at ElementFinder._this.(anonymous function) [as sendKeys] (/Users/adolfocabrera/Mavrix/protractor-cucumber-allure/node_modules/protractor/built/element.js:685:22)
         at World.<anonymous> (/Users/adolfocabrera/Mavrix/protractor-cucumber-allure/StepDefinitions/search.js:9:30)
         at _combinedTickCallback (internal/process/next_tick.js:67:7)

2) Scenario: Cucumber Google - Features/cucumber.feature:4
   Step: When I type "cucumber" - Features/cucumber.feature:6
   Step Definition: StepDefinitions/search.js:8
   Message:
     NoSuchElementError: No element found using locator: By(css selector, input[name='NotElementFound'])
         at WebDriverError (/Users/adolfocabrera/Mavrix/protractor-cucumber-allure/node_modules/selenium-webdriver/error.js:26:26)
         at NoSuchElementError (/Users/adolfocabrera/Mavrix/protractor-cucumber-allure/node_modules/selenium-webdriver/error.js:229:26)
         at /Users/adolfocabrera/Mavrix/protractor-cucumber-allure/node_modules/protractor/built/element.js:662:27
         at Promise.invokeCallback_ (/Users/adolfocabrera/Mavrix/protractor-cucumber-allure/node_modules/selenium-webdriver/lib/promise.js:1329:14)
         at TaskQueue.execute_ (/Users/adolfocabrera/Mavrix/protractor-cucumber-allure/node_modules/selenium-webdriver/lib/promise.js:2790:14)
         at TaskQueue.executeNext_ (/Users/adolfocabrera/Mavrix/protractor-cucumber-allure/node_modules/selenium-webdriver/lib/promise.js:2773:21)
         at /Users/adolfocabrera/Mavrix/protractor-cucumber-allure/node_modules/selenium-webdriver/lib/promise.js:2652:27
         at /Users/adolfocabrera/Mavrix/protractor-cucumber-allure/node_modules/selenium-webdriver/lib/promise.js:639:7
         at process._tickCallback (internal/process/next_tick.js:103:7)
     Error
         at ElementArrayFinder.applyAction_ (/Users/adolfocabrera/Mavrix/protractor-cucumber-allure/node_modules/protractor/built/element.js:371:27)
         at ElementArrayFinder._this.(anonymous function) [as sendKeys] (/Users/adolfocabrera/Mavrix/protractor-cucumber-allure/node_modules/protractor/built/element.js:83:30)
         at ElementFinder._this.(anonymous function) [as sendKeys] (/Users/adolfocabrera/Mavrix/protractor-cucumber-allure/node_modules/protractor/built/element.js:685:22)
         at World.<anonymous> (/Users/adolfocabrera/Mavrix/protractor-cucumber-allure/StepDefinitions/search.js:9:30)
         at _combinedTickCallback (internal/process/next_tick.js:67:7)

3) Scenario: Protractor Google - Features/protractor.feature:4
   Step: When I type "protractor" - Features/protractor.feature:6
   Step Definition: StepDefinitions/search.js:8
   Message:
     NoSuchElementError: No element found using locator: By(css selector, input[name='NotElementFound'])
         at WebDriverError (/Users/adolfocabrera/Mavrix/protractor-cucumber-allure/node_modules/selenium-webdriver/error.js:26:26)
         at NoSuchElementError (/Users/adolfocabrera/Mavrix/protractor-cucumber-allure/node_modules/selenium-webdriver/error.js:229:26)
         at /Users/adolfocabrera/Mavrix/protractor-cucumber-allure/node_modules/protractor/built/element.js:662:27
         at Promise.invokeCallback_ (/Users/adolfocabrera/Mavrix/protractor-cucumber-allure/node_modules/selenium-webdriver/lib/promise.js:1329:14)
         at TaskQueue.execute_ (/Users/adolfocabrera/Mavrix/protractor-cucumber-allure/node_modules/selenium-webdriver/lib/promise.js:2790:14)
         at TaskQueue.executeNext_ (/Users/adolfocabrera/Mavrix/protractor-cucumber-allure/node_modules/selenium-webdriver/lib/promise.js:2773:21)
         at /Users/adolfocabrera/Mavrix/protractor-cucumber-allure/node_modules/selenium-webdriver/lib/promise.js:2652:27
         at /Users/adolfocabrera/Mavrix/protractor-cucumber-allure/node_modules/selenium-webdriver/lib/promise.js:639:7
         at process._tickCallback (internal/process/next_tick.js:103:7)
     Error
         at ElementArrayFinder.applyAction_ (/Users/adolfocabrera/Mavrix/protractor-cucumber-allure/node_modules/protractor/built/element.js:371:27)
         at ElementArrayFinder._this.(anonymous function) [as sendKeys] (/Users/adolfocabrera/Mavrix/protractor-cucumber-allure/node_modules/protractor/built/element.js:83:30)
         at ElementFinder._this.(anonymous function) [as sendKeys] (/Users/adolfocabrera/Mavrix/protractor-cucumber-allure/node_modules/protractor/built/element.js:685:22)
         at World.<anonymous> (/Users/adolfocabrera/Mavrix/protractor-cucumber-allure/StepDefinitions/search.js:9:30)
         at _combinedTickCallback (internal/process/next_tick.js:67:7)

3 scenarios (3 failed)
12 steps (3 failed, 6 skipped, 3 passed)
0m00.181s
Report created successfully!
[09:42:55] I/launcher - 0 instance(s) of WebDriver still running
[09:42:55] I/launcher - chromeANY #01 failed 3 test(s)
[09:42:55] I/launcher - overall: 3 failed spec(s)
[09:42:55] E/launcher - Process exited with error code 1
npm ERR! Test failed.  See above for more details.
```

But using protractor 3.3.0 is not a proper solution for me because I am using a selenium remote grid to run the test and this version of protractor is not compatible to run the test. I get a weird error 

```
'<html>\n<head><title>301 Moved Permanently</title></head>\n<body bgcolor="white">\n<center><h1>301 Moved Permanently</h1></center>\n<hr><center>nginx/1.4.6 (Ubuntu)</center>\n</body>\n</html>\n
```

**Comment by igniteram** [comment]
@aluzardo I have done some investigation and turns it out this is an issue with the recent protractor versions. 

This is mainly due to protractor's `uncaught exception` handling, cucumber listener's catch it after the protractor's exception hence causing the step definition to fail abruptly. 

The issues - https://github.com/angular/protractor/issues/3553  and https://github.com/angular/protractor/issues/3491 have been raised already. Soon it should be resolved in coming releases!

**Comment by igniteram** [comment]
tagged it as external bug and pretty good discussions are going on the respective issues logged in protractor repo, I would still keep it open until it is fixed!

**Comment by igniteram** [comment]
This issue should be fixed with https://github.com/angular/protractor/pull/3608, hence closing it!
